#!/usr/bin/env tsx
// ============================================================
// One-time codegen: reads every CSV under /data/sources/recall and
// /data/sources/pocket-tradesman, infers a column list per file
// (schema-infer.ts), and emits the Field Mode reference-table
// migration SQL. Run again and diff if a new source file is added;
// this script never touches the database itself.
//
// Usage: npx tsx scripts/field-mode/gen-migration.ts > /tmp/out.sql
// (the actual migration file committed to the repo is hand-reviewed
// output of this script, not generated on every run)
// ============================================================
import * as fs from 'fs'
import * as path from 'path'
import { parseCsv } from './lib/csv'
import { inferColumns, ColumnDef } from './lib/schema-infer'
import { allFileTablePairs } from './lib/table-map'

const ROOT = path.resolve(__dirname, '..', '..')
const RECALL_DIR = path.join(ROOT, 'data', 'sources', 'recall')
const POCKET_DIR = path.join(ROOT, 'data', 'sources', 'pocket-tradesman')

function pgTypeSql(t: ColumnDef['pgType']): string {
  if (t === 'NUMERIC') return 'NUMERIC'
  if (t === 'BOOLEAN') return 'BOOLEAN'
  return 'TEXT'
}

function tableSql(table: string, csvColumns: ColumnDef[], sourceDir: 'recall' | 'pocket-tradesman'): string {
  const lines: string[] = []
  lines.push(`CREATE TABLE IF NOT EXISTS public.${table} (`)
  lines.push(`  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),`)

  for (const col of csvColumns) {
    lines.push(`  ${col.dbColumn} ${pgTypeSql(col.pgType)},`)
  }

  const hasRecallConfidence = csvColumns.some((c) => c.dbColumn === 'recall_confidence')
  if (!hasRecallConfidence) {
    // Batch-1 recall files lack this column (Phase 0 §2.4 finding) — add it, default 'unrated'.
    lines.push(`  recall_confidence TEXT NOT NULL DEFAULT 'unrated',`)
  }

  // Common bookkeeping columns not carried by any CSV (master prompt §3.1).
  lines.push(`  source_page_or_table TEXT,`)
  lines.push(`  verified_at TIMESTAMPTZ,`)
  lines.push(`  import_batch_id UUID NOT NULL,`)
  lines.push(`  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),`)
  lines.push(`  source_file_sha256 TEXT NOT NULL,`)

  // Field Mode importer bookkeeping (§3.2b precedence, §3.3 supersede, §5.5 reject).
  if (!csvColumns.some((c) => c.dbColumn === 'rejected')) lines.push(`  rejected BOOLEAN NOT NULL DEFAULT false,`)
  lines.push(`  rejected_note TEXT,`)
  lines.push(`  superseded_by_batch UUID,`)
  lines.push(`  source_dir TEXT NOT NULL DEFAULT '${sourceDir}'`)

  lines.push(`);`)
  lines.push('')
  lines.push(`ALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY;`)
  lines.push('')
  lines.push(`-- Reference data is global read-only for any authenticated user (master prompt rule 6).`)
  lines.push(`-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).`)
  lines.push(`CREATE POLICY "${table}_read_all" ON public.${table}`)
  lines.push(`  FOR SELECT TO authenticated USING (true);`)
  lines.push('')
  lines.push(`-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.`)
  lines.push(`CREATE POLICY "${table}_write_owner" ON public.${table}`)
  lines.push(`  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());`)
  lines.push('')
  return lines.join('\n')
}

function main() {
  const out: string[] = []
  out.push('-- ============================================================')
  out.push('-- Migration: 20260829_field_mode_reference_tables')
  out.push('-- Field Mode Phase 1 — reference library data layer.')
  out.push('--')
  out.push('-- Generated by scripts/field-mode/gen-migration.ts from the CSV')
  out.push('-- headers under /data/sources/recall and /data/sources/pocket-tradesman.')
  out.push('-- Column names mirror each CSV\'s header row exactly (master prompt')
  out.push('-- §3.2: "Do not rename or normalize columns"). Do not hand-edit')
  out.push('-- column lists here without re-running the generator and diffing —')
  out.push('-- hand edits will drift from the CSV headers.')
  out.push('--')
  out.push('-- All tables: global SELECT for any authenticated user, write')
  out.push('-- restricted to platform_admin (the owner-level cross-tenant role,')
  out.push('-- confirmed in PHASE_0_FINDINGS.md §2.3). No tenant scoping — this')
  out.push('-- is reference data, not tenant data.')
  out.push('-- ============================================================')
  out.push('')

  for (const { file, table, source } of allFileTablePairs()) {
    const dir = source === 'recall' ? RECALL_DIR : POCKET_DIR
    const full = path.join(dir, file)
    const text = fs.readFileSync(full, 'utf8')
    const csv = parseCsv(text)
    const cols = inferColumns(csv)
    out.push(`-- Source: data/sources/${source}/${file} (${csv.rows.length} rows)`)
    out.push(tableSql(table, cols, source))
  }

  out.push('-- ============================================================')
  out.push('-- Verification event log (append-only). Master prompt §3.4.')
  out.push('-- ============================================================')
  out.push('CREATE TABLE IF NOT EXISTS public.ref_verification_events (')
  out.push('  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),')
  out.push('  table_name TEXT NOT NULL,')
  out.push('  row_id UUID NOT NULL,')
  out.push('  verified BOOLEAN NOT NULL,')
  out.push('  verified_by TEXT NOT NULL,')
  out.push('  verified_against TEXT NOT NULL,')
  out.push('  note TEXT,')
  out.push('  created_by UUID REFERENCES auth.users(id),')
  out.push('  created_at TIMESTAMPTZ NOT NULL DEFAULT now()')
  out.push(');')
  out.push('')
  out.push('CREATE INDEX IF NOT EXISTS ref_verification_events_table_row_idx')
  out.push('  ON public.ref_verification_events(table_name, row_id);')
  out.push('')
  out.push('ALTER TABLE public.ref_verification_events ENABLE ROW LEVEL SECURITY;')
  out.push('')
  out.push('-- Append-only: readable by any authenticated user (transparency of')
  out.push('-- verification history), insertable only by platform_admin. No')
  out.push('-- UPDATE/DELETE policy exists for anyone — this table is append-only')
  out.push('-- by construction, not just by convention.')
  out.push('CREATE POLICY "ref_verification_events_read_all" ON public.ref_verification_events')
  out.push('  FOR SELECT TO authenticated USING (true);')
  out.push('')
  out.push('CREATE POLICY "ref_verification_events_insert_owner" ON public.ref_verification_events')
  out.push('  FOR INSERT WITH CHECK (public.is_platform_admin());')
  out.push('')

  process.stdout.write(out.join('\n') + '\n')
}

main()
