-- ============================================================
-- Migration: 20260829_field_mode_reference_tables
-- Field Mode Phase 1 — reference library data layer.
--
-- Generated by scripts/field-mode/gen-migration.ts from the CSV
-- headers under /data/sources/recall and /data/sources/pocket-tradesman.
-- Column names mirror each CSV's header row exactly (master prompt
-- §3.2: "Do not rename or normalize columns"). Do not hand-edit
-- column lists here without re-running the generator and diffing —
-- hand edits will drift from the CSV headers.
--
-- All tables: global SELECT for any authenticated user, write
-- restricted to platform_admin (the owner-level cross-tenant role,
-- confirmed in PHASE_0_FINDINGS.md §2.3). No tenant scoping — this
-- is reference data, not tenant data.
-- ============================================================

-- Source: data/sources/recall/ref_flanges_b16_5.csv (132 rows)
CREATE TABLE IF NOT EXISTS public.ref_flanges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  edition TEXT,
  flange_class NUMERIC,
  nps TEXT,
  od_in NUMERIC,
  od_mm NUMERIC,
  thickness_in NUMERIC,
  thickness_mm NUMERIC,
  bolt_circle_in NUMERIC,
  bolt_circle_mm NUMERIC,
  bolt_count NUMERIC,
  bolt_size_in TEXT,
  bolt_hole_in NUMERIC,
  bolt_hole_mm NUMERIC,
  rf_dia_in NUMERIC,
  rf_dia_mm NUMERIC,
  rf_height_in NUMERIC,
  lth_wn_in NUMERIC,
  lth_wn_mm NUMERIC,
  lth_so_in NUMERIC,
  lth_so_mm NUMERIC,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT NOT NULL DEFAULT 'unrated',
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_flanges ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_flanges_read_all" ON public.ref_flanges
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_flanges_write_owner" ON public.ref_flanges
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_flange_hubs_b16_5.csv (132 rows)
CREATE TABLE IF NOT EXISTS public.ref_flange_hubs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  flange_class NUMERIC,
  nps TEXT,
  hub_dia_base_x_in NUMERIC,
  hub_dia_base_x_mm NUMERIC,
  hub_dia_bevel_a_in_wn NUMERIC,
  hub_dia_bevel_a_mm_wn NUMERIC,
  slip_on_bore_b_in NUMERIC,
  slip_on_bore_b_mm NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_flange_hubs ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_flange_hubs_read_all" ON public.ref_flange_hubs
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_flange_hubs_write_owner" ON public.ref_flange_hubs
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_flange_weights_b16_5.csv (204 rows)
CREATE TABLE IF NOT EXISTS public.ref_flange_weights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  flange_class NUMERIC,
  nps TEXT,
  flange_type TEXT,
  weight_lb_approx NUMERIC,
  weight_kg_approx NUMERIC,
  tolerance TEXT,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_flange_weights ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_flange_weights_read_all" ON public.ref_flange_weights
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_flange_weights_write_owner" ON public.ref_flange_weights
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_stud_bolts_b16_5.csv (109 rows)
CREATE TABLE IF NOT EXISTS public.ref_stud_bolts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  flange_class NUMERIC,
  nps TEXT,
  stud_dia_in TEXT,
  stud_dia_mm NUMERIC,
  stud_length_in TEXT,
  stud_length_dec_in NUMERIC,
  stud_length_mm NUMERIC,
  studs_per_flange NUMERIC,
  nut_wrench_size_heavy_hex_in NUMERIC,
  nut_wrench_size_mm NUMERIC,
  nut_height_heavy_hex_in NUMERIC,
  tpi NUMERIC,
  thread_series TEXT,
  check_min_plausible_length_in NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_stud_bolts ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_stud_bolts_read_all" ON public.ref_stud_bolts
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_stud_bolts_write_owner" ON public.ref_stud_bolts
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_bw_fittings_b16_9.csv (166 rows)
CREATE TABLE IF NOT EXISTS public.ref_bw_fittings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  edition TEXT,
  nps TEXT,
  od_in NUMERIC,
  od_mm NUMERIC,
  fitting_type TEXT,
  dimension_label TEXT,
  center_to_end_in NUMERIC,
  center_to_end_mm NUMERIC,
  derived BOOLEAN,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT NOT NULL DEFAULT 'unrated',
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_bw_fittings ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_bw_fittings_read_all" ON public.ref_bw_fittings
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_bw_fittings_write_owner" ON public.ref_bw_fittings
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_reducing_tee_outlet_b16_9.csv (73 rows)
CREATE TABLE IF NOT EXISTS public.ref_reducing_tee_outlets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  run_nps TEXT,
  outlet_nps TEXT,
  run_center_to_end_c_in NUMERIC,
  run_center_to_end_c_mm NUMERIC,
  outlet_center_to_end_m_in NUMERIC,
  outlet_center_to_end_m_mm NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_reducing_tee_outlets ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_reducing_tee_outlets_read_all" ON public.ref_reducing_tee_outlets
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_reducing_tee_outlets_write_owner" ON public.ref_reducing_tee_outlets
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_sw_fittings_b16_11.csv (24 rows)
CREATE TABLE IF NOT EXISTS public.ref_sw_fittings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  fitting_class NUMERIC,
  nps TEXT,
  pipe_od_in NUMERIC,
  socket_bore_min_in NUMERIC,
  socket_bore_max_in NUMERIC,
  socket_bore_min_mm NUMERIC,
  socket_bore_max_mm NUMERIC,
  socket_depth_j_min_in NUMERIC,
  socket_depth_j_min_mm NUMERIC,
  socket_wall_c_min_in NUMERIC,
  socket_wall_c_min_mm NUMERIC,
  fitting_bore_d_in NUMERIC,
  fitting_bore_d_mm NUMERIC,
  ctr_to_socket_bottom_a_90_tee_in NUMERIC,
  ctr_to_socket_bottom_a_90_tee_mm NUMERIC,
  ctr_to_socket_bottom_45_in NUMERIC,
  ctr_to_socket_bottom_45_mm NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_sw_fittings ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_sw_fittings_read_all" ON public.ref_sw_fittings
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_sw_fittings_write_owner" ON public.ref_sw_fittings
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_sw_couplings_b16_11.csv (12 rows)
CREATE TABLE IF NOT EXISTS public.ref_sw_couplings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  nps TEXT,
  full_coupling_length_w_in NUMERIC,
  full_coupling_length_w_mm NUMERIC,
  socket_depth_j_min_in NUMERIC,
  center_wall_min_in NUMERIC,
  half_coupling_length_approx_in NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_sw_couplings ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_sw_couplings_read_all" ON public.ref_sw_couplings
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_sw_couplings_write_owner" ON public.ref_sw_couplings
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_threaded_fittings_ctr_to_end.csv (56 rows)
CREATE TABLE IF NOT EXISTS public.ref_threaded_fittings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  nps TEXT,
  ctr_to_end_a_90_tee_in NUMERIC,
  ctr_to_end_a_90_tee_mm NUMERIC,
  ctr_to_end_45_in NUMERIC,
  ctr_to_end_45_mm NUMERIC,
  thread_engagement_see TEXT,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_threaded_fittings ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_threaded_fittings_read_all" ON public.ref_threaded_fittings
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_threaded_fittings_write_owner" ON public.ref_threaded_fittings
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_npt_threads_b1_20_1.csv (19 rows)
CREATE TABLE IF NOT EXISTS public.ref_npt_threads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  nps TEXT,
  tpi NUMERIC,
  pitch_in NUMERIC,
  pitch_mm NUMERIC,
  pipe_od_in NUMERIC,
  pipe_od_mm NUMERIC,
  handtight_l1_in NUMERIC,
  handtight_l1_mm NUMERIC,
  handtight_turns NUMERIC,
  effective_thread_l2_in NUMERIC,
  effective_thread_l2_mm NUMERIC,
  wrench_makeup_l3_in NUMERIC,
  wrench_makeup_turns NUMERIC,
  total_makeup_l1_plus_l3_in NUMERIC,
  taper TEXT,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_npt_threads ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_npt_threads_read_all" ON public.ref_npt_threads
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_npt_threads_write_owner" ON public.ref_npt_threads
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_bolt_drill_tap.csv (60 rows)
CREATE TABLE IF NOT EXISTS public.ref_bolt_drill_tap (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  thread TEXT,
  series TEXT,
  nominal_dia_in NUMERIC,
  tpi NUMERIC,
  tap_drill TEXT,
  tap_drill_in NUMERIC,
  tap_drill_mm NUMERIC,
  clearance_close_in NUMERIC,
  clearance_free_in NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_bolt_drill_tap ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_bolt_drill_tap_read_all" ON public.ref_bolt_drill_tap
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_bolt_drill_tap_write_owner" ON public.ref_bolt_drill_tap
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_wrench_sizes.csv (27 rows)
CREATE TABLE IF NOT EXISTS public.ref_wrench_sizes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  item TEXT,
  size TEXT,
  heavy_hex_across_flats_in TEXT,
  heavy_hex_across_flats_mm NUMERIC,
  regular_hex_across_flats_in NUMERIC,
  heavy_hex_nut_height_in NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_wrench_sizes ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_wrench_sizes_read_all" ON public.ref_wrench_sizes
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_wrench_sizes_write_owner" ON public.ref_wrench_sizes
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_shackles.csv (17 rows)
CREATE TABLE IF NOT EXISTS public.ref_shackles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  bow_size_in TEXT,
  bow_dia_in NUMERIC,
  bow_dia_mm NUMERIC,
  wll_short_tons NUMERIC,
  wll_kg NUMERIC,
  inside_width_at_pin_in NUMERIC,
  inside_width_at_pin_mm NUMERIC,
  pin_dia_in NUMERIC,
  pin_dia_mm NUMERIC,
  inside_length_in NUMERIC,
  inside_length_mm NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_shackles ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_shackles_read_all" ON public.ref_shackles
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_shackles_write_owner" ON public.ref_shackles
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_sling_leg_factors.csv (13 rows)
CREATE TABLE IF NOT EXISTS public.ref_sling_leg_factors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  angle_from_horizontal_deg NUMERIC,
  angle_from_vertical_deg NUMERIC,
  leg_load_multiplier NUMERIC,
  note TEXT,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_sling_leg_factors ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_sling_leg_factors_read_all" ON public.ref_sling_leg_factors
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_sling_leg_factors_write_owner" ON public.ref_sling_leg_factors
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_snatch_block_factors.csv (11 rows)
CREATE TABLE IF NOT EXISTS public.ref_snatch_block_factors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  angle_between_lines_deg NUMERIC,
  block_load_multiplier NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_snatch_block_factors ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_snatch_block_factors_read_all" ON public.ref_snatch_block_factors
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_snatch_block_factors_write_owner" ON public.ref_snatch_block_factors
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_wire_rope_sling_swl.csv (16 rows)
CREATE TABLE IF NOT EXISTS public.ref_wire_rope_slings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  rope_dia_in TEXT,
  rope_dia_mm NUMERIC,
  swl_vertical_short_tons NUMERIC,
  swl_choker_short_tons NUMERIC,
  swl_basket_vertical_short_tons NUMERIC,
  nominal_breaking_strength_short_tons NUMERIC,
  rule_of_thumb_swl_tons_8xd2 NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_wire_rope_slings ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_wire_rope_slings_read_all" ON public.ref_wire_rope_slings
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_wire_rope_slings_write_owner" ON public.ref_wire_rope_slings
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_synthetic_sling_wll.csv (18 rows)
CREATE TABLE IF NOT EXISTS public.ref_synthetic_slings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  sling_type TEXT,
  size_or_color TEXT,
  wll_vertical_lb NUMERIC,
  wll_choker_lb NUMERIC,
  wll_basket_vertical_lb NUMERIC,
  wll_vertical_kg NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_synthetic_slings ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_synthetic_slings_read_all" ON public.ref_synthetic_slings
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_synthetic_slings_write_owner" ON public.ref_synthetic_slings
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_chain_sling_wll.csv (17 rows)
CREATE TABLE IF NOT EXISTS public.ref_chain_slings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  chain_grade TEXT,
  chain_size_in TEXT,
  chain_size_mm NUMERIC,
  wll_single_vertical_lb NUMERIC,
  wll_single_vertical_kg NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_chain_slings ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_chain_slings_read_all" ON public.ref_chain_slings
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_chain_slings_write_owner" ON public.ref_chain_slings
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_hand_signals.csv (20 rows)
CREATE TABLE IF NOT EXISTS public.ref_hand_signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  signal TEXT,
  description TEXT,
  image_asset TEXT,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_hand_signals ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_hand_signals_read_all" ON public.ref_hand_signals
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_hand_signals_write_owner" ON public.ref_hand_signals
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_conversion_factors.csv (54 rows)
CREATE TABLE IF NOT EXISTS public.ref_conversion_factors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  category TEXT,
  from_unit TEXT,
  to_unit TEXT,
  multiply_by TEXT,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_conversion_factors ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_conversion_factors_read_all" ON public.ref_conversion_factors
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_conversion_factors_write_owner" ON public.ref_conversion_factors
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_water_head_pressure.csv (42 rows)
CREATE TABLE IF NOT EXISTS public.ref_water_head_pressure (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  head_ft NUMERIC,
  head_m NUMERIC,
  pressure_psi NUMERIC,
  pressure_kpa NUMERIC,
  recall_confidence TEXT,
  note TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_water_head_pressure ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_water_head_pressure_read_all" ON public.ref_water_head_pressure
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_water_head_pressure_write_owner" ON public.ref_water_head_pressure
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_gas_properties.csv (26 rows)
CREATE TABLE IF NOT EXISTS public.ref_gas_properties (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  gas TEXT,
  formula TEXT,
  lel_pct_vol NUMERIC,
  uel_pct_vol NUMERIC,
  vapor_density_air_1 NUMERIC,
  heavier_than_air TEXT,
  exposure_limits_note TEXT,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_gas_properties ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_gas_properties_read_all" ON public.ref_gas_properties
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_gas_properties_write_owner" ON public.ref_gas_properties
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_material_weights.csv (35 rows)
CREATE TABLE IF NOT EXISTS public.ref_material_weights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  material TEXT,
  density_lb_per_ft3 NUMERIC,
  density_kg_per_m3 NUMERIC,
  specific_gravity NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_material_weights ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_material_weights_read_all" ON public.ref_material_weights
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_material_weights_write_owner" ON public.ref_material_weights
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/recall/ref_plate_steel_weights.csv (19 rows)
CREATE TABLE IF NOT EXISTS public.ref_plate_steel_weights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  thickness_in TEXT,
  thickness_mm NUMERIC,
  weight_lb_per_ft2 NUMERIC,
  weight_kg_per_m2 NUMERIC,
  weight_lb_per_4x8_sheet NUMERIC,
  recall_confidence TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'recall'
);

ALTER TABLE public.ref_plate_steel_weights ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_plate_steel_weights_read_all" ON public.ref_plate_steel_weights
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_plate_steel_weights_write_owner" ON public.ref_plate_steel_weights
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_eye_bolts_pocket_tradesman.csv (10 rows)
CREATE TABLE IF NOT EXISTS public.ref_eye_bolts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  stock_dia_in TEXT,
  swl_vertical_lb NUMERIC,
  swl_60deg_lb NUMERIC,
  swl_45deg_lb NUMERIC,
  swl_below_45_lb TEXT,
  note TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_eye_bolts ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_eye_bolts_read_all" ON public.ref_eye_bolts
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_eye_bolts_write_owner" ON public.ref_eye_bolts
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_fibre_rope_swl_pocket_tradesman.csv (9 rows)
CREATE TABLE IF NOT EXISTS public.ref_fibre_rope_slings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  rope_dia_in TEXT,
  manila_lb NUMERIC,
  nylon_lb NUMERIC,
  polypropylene_lb NUMERIC,
  polyester_lb NUMERIC,
  polyethylene_lb NUMERIC,
  rule_of_thumb TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_fibre_rope_slings ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_fibre_rope_slings_read_all" ON public.ref_fibre_rope_slings
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_fibre_rope_slings_write_owner" ON public.ref_fibre_rope_slings
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_wire_rope_clips_pocket_tradesman.csv (14 rows)
CREATE TABLE IF NOT EXISTS public.ref_wire_rope_clips (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  rope_dia_in TEXT,
  min_clips NUMERIC,
  turn_back_from_thimble_in TEXT,
  turn_back_mm NUMERIC,
  torque_ft_lb_unlubricated NUMERIC,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_wire_rope_clips ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_wire_rope_clips_read_all" ON public.ref_wire_rope_clips
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_wire_rope_clips_write_owner" ON public.ref_wire_rope_clips
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_hydro_test_pressures_pocket_tradesman.csv (7 rows)
CREATE TABLE IF NOT EXISTS public.ref_hydro_test_pressures (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  flange_class NUMERIC,
  max_test_psi NUMERIC,
  max_test_kpa NUMERIC,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_hydro_test_pressures ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_hydro_test_pressures_read_all" ON public.ref_hydro_test_pressures
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_hydro_test_pressures_write_owner" ON public.ref_hydro_test_pressures
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_pancake_thickness_pocket_tradesman.csv (54 rows)
CREATE TABLE IF NOT EXISTS public.ref_pancake_thickness (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  pipe_size_nps NUMERIC,
  test_pressure_psi_from NUMERIC,
  test_pressure_psi_to NUMERIC,
  plate_thickness_in TEXT,
  plate_thickness_mm NUMERIC,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_pancake_thickness ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_pancake_thickness_read_all" ON public.ref_pancake_thickness
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_pancake_thickness_write_owner" ON public.ref_pancake_thickness
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_valve_face_to_face_pocket_tradesman.csv (75 rows)
CREATE TABLE IF NOT EXISTS public.ref_valve_face_to_face (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  valve_type TEXT,
  flange_class NUMERIC,
  nps NUMERIC,
  face_to_face_mm NUMERIC,
  face_to_face_in NUMERIC,
  book_note TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_valve_face_to_face ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_valve_face_to_face_read_all" ON public.ref_valve_face_to_face
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_valve_face_to_face_write_owner" ON public.ref_valve_face_to_face
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_abbreviations_pocket_tradesman.csv (28 rows)
CREATE TABLE IF NOT EXISTS public.ref_abbreviations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  abbrev TEXT,
  meaning TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_abbreviations ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_abbreviations_read_all" ON public.ref_abbreviations
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_abbreviations_write_owner" ON public.ref_abbreviations
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_formulas_pocket_tradesman.csv (13 rows)
CREATE TABLE IF NOT EXISTS public.ref_formulas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  name TEXT,
  text TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_formulas ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_formulas_read_all" ON public.ref_formulas
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_formulas_write_owner" ON public.ref_formulas
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_chain_slings_pocket_tradesman.csv (8 rows)
CREATE TABLE IF NOT EXISTS public.ref_chain_slings_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  chain_size_in TEXT,
  single_vertical_lb NUMERIC,
  single_choker_lb NUMERIC,
  single_basket_vertical_lb NUMERIC,
  two_leg_60deg_lb NUMERIC,
  two_leg_45deg_lb NUMERIC,
  two_leg_30deg_lb NUMERIC,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_chain_slings_book ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_chain_slings_book_read_all" ON public.ref_chain_slings_book
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_chain_slings_book_write_owner" ON public.ref_chain_slings_book
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_flange_bolting_pocket_tradesman.csv (80 rows)
CREATE TABLE IF NOT EXISTS public.ref_flange_bolting_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  flange_class NUMERIC,
  nps TEXT,
  wrench_size_in TEXT,
  wrench_size_dec_in NUMERIC,
  stud_count NUMERIC,
  stud_dia_in TEXT,
  rf_stud_length_in TEXT,
  rf_stud_length_dec_in NUMERIC,
  rf_stud_length_mm NUMERIC,
  gasket_id_in TEXT,
  gasket_od_in TEXT,
  flange_diam_in TEXT,
  flange_diam_dec_in NUMERIC,
  rtj_stud_length_in TEXT,
  rtj_stud_length_dec_in NUMERIC,
  ring_no TEXT,
  book_note TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_flange_bolting_book ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_flange_bolting_book_read_all" ON public.ref_flange_bolting_book
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_flange_bolting_book_write_owner" ON public.ref_flange_bolting_book
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_material_weights_pocket_tradesman.csv (57 rows)
CREATE TABLE IF NOT EXISTS public.ref_material_weights_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  material TEXT,
  weight_as_printed TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_material_weights_book ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_material_weights_book_read_all" ON public.ref_material_weights_book
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_material_weights_book_write_owner" ON public.ref_material_weights_book
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_nylon_web_slings_pocket_tradesman.csv (6 rows)
CREATE TABLE IF NOT EXISTS public.ref_synthetic_slings_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  web_width_in NUMERIC,
  single_vertical_lb NUMERIC,
  single_choker_lb NUMERIC,
  single_basket_vertical_lb NUMERIC,
  two_leg_60deg_lb NUMERIC,
  two_leg_45deg_lb NUMERIC,
  two_leg_30deg_lb NUMERIC,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_synthetic_slings_book ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_synthetic_slings_book_read_all" ON public.ref_synthetic_slings_book
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_synthetic_slings_book_write_owner" ON public.ref_synthetic_slings_book
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_reducing_tee_outlet_pocket_tradesman.csv (40 rows)
CREATE TABLE IF NOT EXISTS public.ref_reducing_tee_outlets_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  run_nps NUMERIC,
  outlet_nps NUMERIC,
  outlet_center_to_end_m_mm NUMERIC,
  outlet_center_to_end_m_in NUMERIC,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_reducing_tee_outlets_book ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_reducing_tee_outlets_book_read_all" ON public.ref_reducing_tee_outlets_book
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_reducing_tee_outlets_book_write_owner" ON public.ref_reducing_tee_outlets_book
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_shackles_pocket_tradesman.csv (20 rows)
CREATE TABLE IF NOT EXISTS public.ref_shackles_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  bow_size_in TEXT,
  inside_width_at_pin_in TEXT,
  inside_width_at_pin_dec_in NUMERIC,
  inside_width_at_pin_mm NUMERIC,
  swl_single_vertical_lb NUMERIC,
  swl_short_tons NUMERIC,
  swl_kg NUMERIC,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_shackles_book ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_shackles_book_read_all" ON public.ref_shackles_book
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_shackles_book_write_owner" ON public.ref_shackles_book
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_wire_rope_slings_pocket_tradesman.csv (15 rows)
CREATE TABLE IF NOT EXISTS public.ref_wire_rope_slings_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  rope_dia_in TEXT,
  single_vertical_lb NUMERIC,
  single_choker_lb NUMERIC,
  single_basket_vertical_lb NUMERIC,
  two_leg_60deg_lb NUMERIC,
  two_leg_45deg_lb NUMERIC,
  two_leg_30deg_lb NUMERIC,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_wire_rope_slings_book ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_wire_rope_slings_book_read_all" ON public.ref_wire_rope_slings_book
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_wire_rope_slings_book_write_owner" ON public.ref_wire_rope_slings_book
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_wn_flange_lth_pocket_tradesman.csv (40 rows)
CREATE TABLE IF NOT EXISTS public.ref_wn_flange_lth_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  flange_class NUMERIC,
  nps NUMERIC,
  lth_wn_incl_rf_mm NUMERIC,
  lth_wn_incl_rf_in NUMERIC,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_wn_flange_lth_book ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_wn_flange_lth_book_read_all" ON public.ref_wn_flange_lth_book
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_wn_flange_lth_book_write_owner" ON public.ref_wn_flange_lth_book
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- Source: data/sources/pocket-tradesman/ref_hand_signals_pocket_tradesman.csv (24 rows)
CREATE TABLE IF NOT EXISTS public.ref_hand_signals_book (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  standard TEXT,
  signal TEXT,
  edition TEXT,
  source_doc TEXT,
  verified BOOLEAN,
  verified_by TEXT,
  verified_against TEXT,
  recall_confidence TEXT,
  source_page_or_table TEXT,
  verified_at TIMESTAMPTZ,
  import_batch_id UUID NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_file_sha256 TEXT NOT NULL,
  rejected BOOLEAN NOT NULL DEFAULT false,
  rejected_note TEXT,
  superseded_by_batch UUID,
  source_dir TEXT NOT NULL DEFAULT 'pocket-tradesman'
);

ALTER TABLE public.ref_hand_signals_book ENABLE ROW LEVEL SECURITY;

-- Reference data is global read-only for any authenticated user (master prompt rule 6).
-- Matches the existing code_registry read-policy convention (20260815_code_registry.sql).
CREATE POLICY "ref_hand_signals_book_read_all" ON public.ref_hand_signals_book
  FOR SELECT TO authenticated USING (true);

-- Only platform_admin (the owner-level cross-tenant role confirmed in Phase 0 §2.3) may write.
CREATE POLICY "ref_hand_signals_book_write_owner" ON public.ref_hand_signals_book
  FOR ALL USING (public.is_platform_admin()) WITH CHECK (public.is_platform_admin());

-- ============================================================
-- Verification event log (append-only). Master prompt §3.4.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.ref_verification_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name TEXT NOT NULL,
  row_id UUID NOT NULL,
  verified BOOLEAN NOT NULL,
  verified_by TEXT NOT NULL,
  verified_against TEXT NOT NULL,
  note TEXT,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ref_verification_events_table_row_idx
  ON public.ref_verification_events(table_name, row_id);

ALTER TABLE public.ref_verification_events ENABLE ROW LEVEL SECURITY;

-- Append-only: readable by any authenticated user (transparency of
-- verification history), insertable only by platform_admin. No
-- UPDATE/DELETE policy exists for anyone — this table is append-only
-- by construction, not just by convention.
CREATE POLICY "ref_verification_events_read_all" ON public.ref_verification_events
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "ref_verification_events_insert_owner" ON public.ref_verification_events
  FOR INSERT WITH CHECK (public.is_platform_admin());

